# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c28513a466242c6c6b618eb65fd26fb54f0cc819f1f7fad42259136534f9b8dd4dedca5187978ab5f4f3219d0e13dba0f05e61e5722e022697ab0e31f6b5099

test:
  secret_key_base: dc3ac3fc3e98a644d5c8113109e42fdcc43ad0c2f9ce34ea8ef40ff533b137dca1bd7987dc38bfe8f8fe911f4c5b5b51b450b44d87e337c8c8c12fff0efb289e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
